AWSTemplateFormatVersion: '2010-09-09'
Description: >
  Create the stream for the rivers.

Parameters:
  Stage:
    Type: String
    Description: stage/environment discriminator to allow instantiating multiple stacks in the same account/region


Resources:
  RapidsStream:
    Type: AWS::Kinesis::Stream
    Properties:
      Name: !Join [ -, [Rapids, !Ref "Stage"]]
      ShardCount: 1

  ControlStream:
    Type: AWS::Kinesis::Stream
    Properties:
      Name: !Join [ -, [Control, !Ref "Stage"]]
      ShardCount: 1

Outputs:
  RapidsStreamArn:
    Value: 
      !GetAtt RapidsStream.Arn
    Export:
      Name: 
        !Join [-, [RapidsArn, !Ref 'Stage']]

  RapidsStreamName:
    Value: !Ref RapidsStream

  ControlStreamArn:
    Value: 
      !GetAtt ControlStream.Arn
    Export:
      Name: 
        !Join [-, [ControlArn, !Ref 'Stage']]

  ControlStreamName:
    Value: !Ref ControlStream
