AWSTemplateFormatVersion: '2010-09-09'
Description: >
  Create the stream for the rivers.

Parameters:
  Stage:
    Type: String
    Description: stage/environment discriminator to allow instantiating multiple stacks in the same account/region


Resources:
  RapidsStream:
    Type: AWS::Kinesis::Stream
    Properties:
      Name: !Join [ -, [Rapids, !Ref "Stage"]]
      ShardCount: 1

Outputs:
  StreamArn:
    Value: 
      !GetAtt RapidsStream.Arn
    Export:
      Name: 
        !Join [-, [RapidsArn, !Ref 'Stage']]

  StreamName:
    Value: !Ref RapidsStream
