AWSTemplateFormatVersion: '2010-09-09'
Description: >
  Create some sample rivers

Parameters:
  Stage:
    Type: String
    Description: stage/environment discriminator to allow instantiating multiple stacks in the same account/region


Resources:
  MembershipRiver:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Join [-,[MembershipRiver, !Ref Stage]]

  SegmentationRiver:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Join [-,[SegmentationRiver, !Ref Stage]]

  LocationRiver:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Join [-,[LocationRiver, !Ref Stage]]

  BrandRiver:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Join [-,[BrandRiver, !Ref Stage]]

  OfferEngineRiver:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Join [-,[OfferEngineRiver, !Ref Stage]]



Outputs:

  MembershipRiverArn:
    Value: 
      !GetAtt MembershipRiver.Arn
    Export:
      Name: 
        !Join [-, [MembershipRiverArn, !Ref 'Stage']]

  SegmentationRiverArn:
    Value: 
      !GetAtt SegmentationRiver.Arn
    Export:
      Name: 
        !Join [-, [SegmentationRiverArn, !Ref 'Stage']]

  LocationRiverArn:
    Value: 
      !GetAtt LocationRiver.Arn
    Export:
      Name: 
        !Join [-, [LocationRiverArn, !Ref 'Stage']]

  BrandRiverArn:
    Value: 
      !GetAtt BrandRiver.Arn
    Export:
      Name: 
        !Join [-, [BrandRiverArn, !Ref 'Stage']]

  OfferEngineRiverArn:
    Value: 
      !GetAtt OfferEngineRiver.Arn
    Export:
      Name: 
        !Join [-, [OfferEngineRiverArn, !Ref 'Stage']]
