AWSTemplateFormatVersion: '2010-09-09'
Description: >
  Create some sample rivers

Parameters:
  Stage:
    Type: String
    Description: stage/environment discriminator to allow instantiating multiple stacks in the same account/region


Resources:
  AlphaQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Join [-,[AlphaQ, !Ref Stage]]

  BetaQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Join [-,[BetaQ, !Ref Stage]]


Outputs:

  AlphaQArn:
    Value: 
      !GetAtt AlphaQ.Arn
    Export:
      Name: 
        !Join [-, [AlphaQArn, !Ref 'Stage']]

  BetaQArn:
    Value: 
      !GetAtt BetaQ.Arn
    Export:
      Name: 
        !Join [-, [BetaQArn, !Ref 'Stage']]
