AWSTemplateFormatVersion: '2010-09-09'
Description: >
  Topic to publish rapids events to, for the purposed of filtered subscriptions controlling
  propagation of messages to rivers.

Parameters:
  Stage:
    Type: String
    Description: stage/environment discriminator to allow instantiating multiple stacks in the same account/region

Resources:
  RapidsTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: !Sub Rapids-${Stage}
      TopicName: !Sub Rapids-${Stage}

Outputs:
  TopicArn:
    Value: !Ref RapidsTopic
    Export:
      Name:
        !Join [-, [TopicArn, !Ref 'Stage']]