AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: >
  Step function hello world with SAM!
Globals:
  Function:
    Runtime: "nodejs8.10"

Parameters:
  Stage: 
    Type: String
    Default: dev

Resources:
  StreamProcessor:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Join [ -, [StreamProcessor, !Ref "Stage"]]
      Handler: control.handler
      CodeUri: src/
      Events:
        StreamEvent:
          Type: Kinesis
          Properties:
            Stream: !Sub 'arn:aws:kinesis:${AWS::Region}:${AWS::AccountId}:stream/Rapids-${Stage}'
            StartingPosition: LATEST
            BatchSize: 10