AWSTemplateFormatVersion: '2010-09-09'
Description: 'Rapid rivers data plane

  '
Globals:
  Function:
    Runtime: nodejs8.10
Parameters:
  Stage:
    Default: dev
    Type: String
Resources:
  BatchForRiver:
    Properties:
      CodeUri: s3://sampack-97068/b4fbf00199e740775a79871460347333
      Environment:
        Variables:
          STAGE:
            Ref: Stage
      FunctionName:
        Fn::Join:
        - '-'
        - - BatchForRiver
          - Ref: Stage
      Handler: batch4river.handler
      Role:
        Fn::GetAtt:
        - BatchForRiverExecutionRole
        - Arn
      Timeout: 10
    Type: AWS::Serverless::Function
  BatchForRiverExecutionRole:
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action: sts:AssumeRole
          Effect: Allow
          Principal:
            Service: lambda.amazonaws.com
        Version: '2012-10-17'
      Path: /
      Policies:
      - PolicyDocument:
          Statement:
          - Action:
            - sqs:ReceiveMessage
            - sqs:GetQueueUrl
            - sqs:DeleteMessage
            Effect: Allow
            Resource: '*'
          Version: '2012-10-17'
        PolicyName: AccessSQS
      - PolicyDocument:
          Statement:
          - Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
            Effect: Allow
            Resource: '*'
          Version: '2012-10-17'
        PolicyName: CreateAndWriteLogs
    Type: AWS::IAM::Role
  StreamProcExecutionRole:
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action: sts:AssumeRole
          Effect: Allow
          Principal:
            Service: lambda.amazonaws.com
        Version: '2012-10-17'
      Path: /
      Policies:
      - PolicyDocument:
          Statement:
          - Action:
            - sns:Publish
            Effect: Allow
            Resource:
              Fn::ImportValue:
                Fn::Join:
                - '-'
                - - TopicArn
                  - Ref: Stage
          Version: '2012-10-17'
        PolicyName: AccessSNS
      - PolicyDocument:
          Statement:
          - Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
            Effect: Allow
            Resource: '*'
          Version: '2012-10-17'
        PolicyName: CreateAndWriteLogs
      - PolicyDocument:
          Statement:
          - Action:
            - dynamodb:Query
            Effect: Allow
            Resource:
              Fn::Sub: arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/Subscriptions-${Stage}/index/SubsForTopic
          Version: '2012-10-17'
        PolicyName: WriteToDDB
      - PolicyDocument:
          Statement:
          - Action:
            - kinesis:GetRecords
            - kinesis:GetShardIterator
            - kinesis:DescribeStream
            - kinesis:ListStreams
            Effect: Allow
            Resource:
              Fn::ImportValue:
                Fn::Join:
                - '-'
                - - RapidsArn
                  - Ref: Stage
          Version: '2012-10-17'
        PolicyName: StreamAccess
    Type: AWS::IAM::Role
  StreamProcessor:
    Properties:
      CodeUri: s3://sampack-97068/b4fbf00199e740775a79871460347333
      Environment:
        Variables:
          STAGE:
            Ref: Stage
          TOPIC_ARN:
            Fn::ImportValue:
              Fn::Join:
              - '-'
              - - TopicArn
                - Ref: Stage
      Events:
        StreamEvent:
          Properties:
            BatchSize: 10
            StartingPosition: LATEST
            Stream:
              Fn::Sub: arn:aws:kinesis:${AWS::Region}:${AWS::AccountId}:stream/Rapids-${Stage}
          Type: Kinesis
      FunctionName:
        Fn::Join:
        - '-'
        - - StreamProcessor
          - Ref: Stage
      Handler: stream.handler
      Role:
        Fn::GetAtt:
        - StreamProcExecutionRole
        - Arn
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
